[package]
name = "aerox_config"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "AeroX 配置管理模块"

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
